### ISSUE TITLE
query of lba_lpdf output

### ISSUE THREAD

**Issue by OscartGiles** [jeff324/Stan_LBA#1]
Hi jeff324,

We're looking at using your lba implementation as the basis for a modelling project. 

I just had a question with regards to lba_lpdf function. 

I've added the following code to the lba_single.stan file, to get the lba_lpdf values out. 

```
generated quantities {
     vector[2] pred;
     real log_lik;
     pred = lba_rng(k,A,v,s,tau);

     log_lik = lba_lpdf(RT | k, A, v, s, tau);
}
```

When I run the lba_single.R file and then check the values with

`rstan::extract(fit)$log_lik`

it returns all positive values. I would have thought all of these should be negative as it is providing the log pdf. Is this not the case?

All the best,

Oscar

**Comment by jeff324** [comment]
Hi Oscar. The function lba_lpdf takes the log of the probability density function. Since densities are not restricted between 0 and 1 (like probabilities), log-likelihoods can be positive. Hope this helps. Let me know if you have any other questions.

Best,
Jeff

**Comment by OscartGiles** [comment]
Ah yes of course, thanks for the help.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
